spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_db
    username: postgres
    password: 5430289a
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true